#!/usr/bin/env bash
#
# One-shot installer for the e-commerce data dashboard.
# Tested on Ubuntu 22.04 LTS.
#
# Usage (on your fresh server, as root or via sudo):
#
#   curl -fsSL https://raw.githubusercontent.com/githubcjx/E-commerce-data-dashboard/main/deploy/install.sh | sudo bash
#
# Or for the security-minded — inspect before running:
#
#   curl -fsSL https://raw.githubusercontent.com/githubcjx/E-commerce-data-dashboard/main/deploy/install.sh -o install.sh
#   less install.sh
#   sudo bash install.sh
#
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/githubcjx/E-commerce-data-dashboard.git}"
INSTALL_DIR="${INSTALL_DIR:-/opt/ec-dashboard}"

# ---- pretty output ----
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
log()  { echo -e "${BLUE}[$(date +%H:%M:%S)]${NC} $*"; }
ok()   { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}!${NC} $*"; }
die()  { echo -e "${RED}✗${NC} $*" >&2; exit 1; }

# ---- 0. sanity ----
[ "$EUID" -eq 0 ] || die "请以 root 身份运行：sudo bash $0"

if ! grep -qiE 'ubuntu|debian' /etc/os-release 2>/dev/null; then
    warn "未检测到 Ubuntu / Debian。脚本仅在 Ubuntu 22.04 上充分测试。"
    read -p "是否继续？[y/N] " yn </dev/tty
    [[ "$yn" =~ ^[Yy]$ ]] || exit 1
fi

MEM_MB=$(awk '/MemTotal/ {printf "%d", $2/1024}' /proc/meminfo)
if [ "$MEM_MB" -lt 1800 ]; then
    warn "服务器内存仅 ${MEM_MB} MB。构建前端时可能 OOM，建议至少 2 GB。"
fi

# ---- 1. apt deps ----
log "更新 apt 包索引..."
DEBIAN_FRONTEND=noninteractive apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    curl git ufw openssl ca-certificates >/dev/null

# ---- 2. Docker ----
if ! command -v docker &>/dev/null; then
    log "安装 Docker（official convenience script）..."
    curl -fsSL https://get.docker.com | sh >/dev/null
fi
ok "$(docker --version)"

if ! docker compose version &>/dev/null; then
    log "安装 Docker Compose 插件..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-compose-plugin >/dev/null \
        || die "Docker Compose 插件安装失败"
fi
ok "$(docker compose version)"

# ---- 3. firewall ----
log "配置 ufw 防火墙（开放 22 / 80 / 443）..."
ufw allow 22/tcp  >/dev/null 2>&1 || true
ufw allow 80/tcp  >/dev/null 2>&1 || true
ufw allow 443/tcp >/dev/null 2>&1 || true
ufw --force enable >/dev/null 2>&1 || true
ok "ufw 已就绪：$(ufw status | head -1)"

# ---- 4. clone / pull ----
if [ -d "$INSTALL_DIR/.git" ]; then
    log "$INSTALL_DIR 已存在，拉取最新代码..."
    cd "$INSTALL_DIR" && git pull --ff-only
else
    log "克隆仓库到 $INSTALL_DIR..."
    git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# ---- 5. .env ----
if [ -f .env ]; then
    ok ".env 已存在，跳过交互配置（如需重置请先删除 $INSTALL_DIR/.env）"
else
    echo
    echo "============================================"
    echo "  生产环境参数（这一步只做一次）"
    echo "============================================"
    echo

    read -p "你的域名（已解析到本服务器；留空就用 IP + HTTP）: " DOMAIN </dev/tty
    read -p "平台管理员用户名 [cjx]: " ADMIN_USER </dev/tty
    ADMIN_USER=${ADMIN_USER:-cjx}

    while true; do
        read -s -p "平台管理员密码（至少 8 位，登录后用这个）: " ADMIN_PASS </dev/tty
        echo
        if [ ${#ADMIN_PASS} -lt 8 ]; then warn "密码至少 8 位，重试"; continue; fi
        read -s -p "再输入一次确认: " ADMIN_PASS2 </dev/tty
        echo
        if [ "$ADMIN_PASS" != "$ADMIN_PASS2" ]; then warn "两次输入不一致，重试"; continue; fi
        break
    done

    JWT_SECRET=$(openssl rand -hex 32)
    PG_PASS=$(openssl rand -hex 24)
    SITE_ADDRESS="${DOMAIN:-:80}"

    umask 077
    cat > .env <<EOF
# Generated by deploy/install.sh on $(date -u +%FT%TZ)
POSTGRES_PASSWORD=$PG_PASS
JWT_SECRET=$JWT_SECRET
PLATFORM_ADMIN_USERNAME=$ADMIN_USER
PLATFORM_ADMIN_PASSWORD=$ADMIN_PASS
SITE_ADDRESS=$SITE_ADDRESS
EOF
    chmod 600 .env
    ok ".env 已生成（权限 600）"
fi

# ---- 6. build & up ----
log "构建并启动容器（首次约 3-5 分钟，下载镜像 + 构建前端）..."
COMPOSE="docker compose -f docker-compose.yml -f deploy/docker-compose.prod.yml"
$COMPOSE pull --quiet 2>/dev/null || true
$COMPOSE up -d --build

# ---- 7. wait for backend ----
log "等待后端服务就绪（最多 2 分钟）..."
for i in {1..60}; do
    if $COMPOSE exec -T backend python -c \
        "import urllib.request,sys; urllib.request.urlopen('http://localhost:8000/api/health',timeout=2)" \
        >/dev/null 2>&1; then
        ok "后端健康检查通过"
        break
    fi
    if [ "$i" -eq 60 ]; then
        warn "后端在 2 分钟内未就绪，用 'docker compose logs backend' 排查"
    fi
    sleep 2
done

# ---- 8. summary ----
SITE_ADDR=$(grep ^SITE_ADDRESS .env | cut -d= -f2)
ADMIN_USER=$(grep ^PLATFORM_ADMIN_USERNAME .env | cut -d= -f2)
PUBLIC_IP=$(curl -fsS --max-time 5 https://ifconfig.me 2>/dev/null || \
            curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || \
            echo "<你的服务器 IP>")

echo
echo "============================================"
echo "  🎉 部署完成"
echo "============================================"
echo
if [ "$SITE_ADDR" != ":80" ]; then
    echo "  访问地址：    https://$SITE_ADDR"
    echo "                Caddy 首次访问时自动申请 Let's Encrypt 证书（10-30s）"
else
    echo "  访问地址：    http://$PUBLIC_IP"
    echo "                （未配域名，HTTP-only。后续可重跑本脚本切到 HTTPS）"
fi
echo
echo "  登录账号：    $ADMIN_USER  /  （你刚才设置的密码）"
echo
echo "  安装目录：    $INSTALL_DIR"
echo "  机器入门：    cd $INSTALL_DIR"
echo
echo "  常用命令："
echo "    查看日志：  docker compose logs -f"
echo "    升级版本：  git pull && $COMPOSE up -d --build"
echo "    重启：      $COMPOSE restart"
echo "    备份 DB：   bash deploy/backup.sh"
echo
echo "  详细手册：    $INSTALL_DIR/deploy/README.md"
echo "============================================"
